DROP TABLE IF EXISTS `#__TENNIS_MENU_OPTIONS`;

DROP TABLE IF EXISTS `#__TENNIS_TARIFF`;

DROP TABLE IF EXISTS `#__TENNIS_COURTS`;

DROP TABLE IF EXISTS `#__TENNIS_FEATURES`;

DROP TABLE IF EXISTS `#__TENNIS_TIMES`;